[user]
username = "maeick"
github_username = "andreweick"
groups = ["sudo", "wheel"]
# REAL password_hash = "$6$VcugxwlWVNK8G/GF$JOrUqw178WeymEugDqPIfQGpedFog2HNJEYuYfpfo.HvjBvOlaX3/OajZwQfgRPcCI12laZ0RkfR9.uDZKd4f/"
password_hash = "$6$AdHNLeqwqojfhuki$3APvnKEXh5Qn2PR8QPHy.pF7m1L5onRnw6Rn2s1tx66GHRBEVgHolKQxQXKKPGW.S3rv47f0yEl6IhMcXA0lt/"

[admin]
username = "admin"
groups = ["sudo", "wheel"]
password_hash = "$6$VcugxwlWVNK8G/GF$JOrUqw178WeymEugDqPIfQGpedFog2HNJEYuYfpfo.HvjBvOlaX3/OajZwQfgRPcCI12laZ0RkfR9.uDZKd4f/"

[network]
timezone = "America/New_York"
default_network_interface = "eth0"

[updates]
# Fedora CoreOS update streams:
# - stable: Production-ready releases, updated every 2 weeks
# - testing: Pre-release versions, updated twice per week
# - next: Development versions with latest features, updated multiple times per week
stream = "stable"
strategy = "periodic"
period = "daily"
reboot_time = "03:00"

[bootc]
# Time when bootc container updates are checked (HH:MM:SS format)
update_time = "02:00:00"
# Wait time in seconds after restart before health check
health_check_wait = 30

[container_registry]
url = "ghcr.io/andreweick/iago"
